"""Database table and index creation."""

from .migrations import migrate_ownership, migrate_request_instances

SQLITE_IDENTITY = 'INTEGER PRIMARY KEY AUTOINCREMENT'
POSTGRES_IDENTITY = 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'

SQLITE_TABLE_SCHEMAS = {
    'users': f"""
        CREATE TABLE IF NOT EXISTS users (
            id {SQLITE_IDENTITY},
            username TEXT NOT NULL UNIQUE,
            email TEXT UNIQUE,
            password_hash TEXT,
            auth_provider TEXT NOT NULL DEFAULT 'local',
            auth_subject TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """,
    'collections': f"""
        CREATE TABLE IF NOT EXISTS collections (
            id {SQLITE_IDENTITY},
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            parent_id INTEGER REFERENCES collections(id) ON DELETE CASCADE,
            sort_order INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """,
    'requests': f"""
        CREATE TABLE IF NOT EXISTS requests (
            id {SQLITE_IDENTITY},
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            method TEXT NOT NULL DEFAULT 'GET',
            url TEXT DEFAULT '',
            headers TEXT DEFAULT '[]',
            body_type TEXT DEFAULT 'none',
            body_content TEXT DEFAULT '',
            body_raw_type TEXT DEFAULT 'application/json',
            form_data TEXT DEFAULT '[]',
            auth_type TEXT DEFAULT 'none',
            auth_data TEXT DEFAULT '{{}}',
            sort_order INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """,
    'request_instances': f"""
        CREATE TABLE IF NOT EXISTS request_instances (
            id {SQLITE_IDENTITY},
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            method TEXT NOT NULL DEFAULT 'GET',
            url TEXT DEFAULT '',
            headers TEXT DEFAULT '[]',
            body_type TEXT DEFAULT 'none',
            body_content TEXT DEFAULT '',
            body_raw_type TEXT DEFAULT 'application/json',
            form_data TEXT DEFAULT '[]',
            auth_type TEXT DEFAULT 'none',
            auth_data TEXT DEFAULT '{{}}',
            response_status INTEGER,
            response_status_text TEXT DEFAULT '',
            response_headers TEXT DEFAULT '{{}}',
            response_body TEXT,
            response_time_ms INTEGER,
            response_size TEXT DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """,
}

POSTGRES_TABLE_SCHEMAS = {
    table_name: schema.replace(SQLITE_IDENTITY, POSTGRES_IDENTITY)
    for table_name, schema in SQLITE_TABLE_SCHEMAS.items()
}

TABLE_SCHEMA_BY_BACKEND = {
    'sqlite': SQLITE_TABLE_SCHEMAS,
    'postgresql': POSTGRES_TABLE_SCHEMAS,
}


def create_tables(cursor, backend='sqlite'):
    """Create persistence tables if they do not already exist."""
    schemas = TABLE_SCHEMA_BY_BACKEND.get(backend)
    if schemas is None:
        raise ValueError(f'Unsupported database backend: {backend}')

    for table_name in ('users', 'collections', 'requests', 'request_instances'):
        cursor.execute(schemas[table_name])


def create_postgres_tables(cursor):
    """Create PostgreSQL persistence tables if they do not already exist."""
    create_tables(cursor, backend='postgresql')


def create_indexes(cursor):
    """Create persistence indexes if they do not already exist."""
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_collections_user_id ON collections(user_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_collections_parent_id ON collections(parent_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_requests_user_id ON requests(user_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_requests_collection_id ON requests(collection_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_request_instances_user_id ON request_instances(user_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_request_instances_request_id ON request_instances(request_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_request_instances_updated_at ON request_instances(updated_at)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_collections_sort_order ON collections(sort_order)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_requests_sort_order ON requests(sort_order)")


def initialize_schema(cursor, backend='sqlite'):
    """Create tables, run migrations, and ensure indexes exist."""
    create_tables(cursor, backend=backend)
    migrate_request_instances(cursor)
    migrate_ownership(cursor)
    create_indexes(cursor)
